language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
script: "./gradlew clean build"
after_success:
  - "$(./gradlew currentVersion | grep -q SNAPSHOT) || ./gradlew publish"
env:
  global:
  - secure: aXvVvRG8Q5cHebFbxetzlnIRIq7Dk8BPn6U9qp41X6Ck8QhH5KVhEGsozybwxt1sGofj+ibZfpOnBOM5ctqxRTZjlVc97HyZiv6aoa8RePqIr3a7WObPGuPqlL93LK/AXOtoDZxTMn2+EwM5UMi9T3gpCj1JElMa8hfbSxElflgzvJKhNbK9a8hm4VvsLgA5+7tuop1KOu/BQwX9dDcCWyNvE/fZYgkthY5mpgvyKFllEd3ziUqcuawt0Ap3/tTJo9GEe8WwFvo8kyulIy70JhiqURXHbzvQdE83VEvYVbV+oH2d2E5lcGLL47g3/Y74dFHMQvuXi2jHdzKIKTUyCkAEu8oOd+UreSp7RhWdVCe3vrv3VZLpgHdnJt1j3LUEktXbRs90FEikSPEBk0DFqBiB3ZZIZsb0Qka3ASsmjXeMPznzSDNTglqlwK2nBxBeh2scf+asOxATYhcMr10W4yKtoeIZoa91WJdG4bjHUutTyGFUd6xdj4+qgTxbjpdmTZ46PmFmikdp4TWYKvtNBPbGsAew4HmSlxFylv/WyLtvP4paM9A83UsTjIPo3Ly3vWtGh9kLd7pRABqO9xv2OVpWN6D6038WOCc23GpNL99kvgjQxu8CzS0WVFLJ7g2ajD/ZRRZGpBmnMkwUFiu5rdS1/YBqM8nr/XOKs4mC9VY=
  - secure: a+GcqdvP1ANorXpYK5S9rWGX+McW/n2E3WK/jimf4gy0ZtWDNS96vPN/vjl5S4ghuZIYySyx8jkjfrxh+4+JigwuTOXPbQaxNCIdkTGGSMjTAPIOEikbF/QaF5gz1PA//AbJlWf4OT8pEHPx6vp3a9VsfI7cjW0byGekGV7vnj78b81+ngjxuPc/5WGPrVh2j4qwIAABBMufwZ4DLFEIjvjLG6mIKXMQwLubgqTp8Oxm+1TJ1pm/8uLZaGrCOUEqg4f4rZWeFkDl45l+cXVBDnzgP9U4qDCPZuatVXJA/dxPXbmf2KPH01YJ/zG8CQPjJmOZ2pIo9DorOJClRFSvonB3CepGVM39/LPtIKnWyaYaAz3xTUcO3MKMwk/oYMhnj6SsHXj2y7Dav4ZOnZ9OrKg6hiXv/MP9cH2ALpRB7gjUgIE/BhfNa3nRMFfgSrHC/jEmlL330IpDOCX5/o4hBXYdTFC+1TLi6Y2M/q9zGkjcYqtAK5q5233Qu7wX5q6h+Vfrv69yholRrda37pjwqoCo8IaEtQFyit69nvmxRR6bm+nw8haMt0rrtppaAVtln19B0zxkGlOcRRmB3vv4X9ouZe+3HZvAPyhTMR5bwBOzDjcEr+XzSaA1tWDnqQhnc4UKr+tjdJRYyamuejnZfhK5zbj0QOyP8JrO6ypmRlQ=
